# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\BufferRP\resources\UI\Login_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Screen(object):
    def setupUi(self, Login_Screen):
        Login_Screen.setObjectName("Login_Screen")
        Login_Screen.resize(1001, 713)
        Login_Screen.setMinimumSize(QtCore.QSize(1001, 713))
        Login_Screen.setMaximumSize(QtCore.QSize(1001, 713))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\BufferRP\\resources\\UI\\Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login_Screen.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Login_Screen)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:white;\n"
"border-style:none;\n"
"border-radius:20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 491, 691))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 491, 691))
        self.label.setStyleSheet("border-radius:20px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Image/RedBanner.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(100, 210, 191, 171))
        self.frame_3.setStyleSheet("border-radius:60px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 151, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Image/Logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(110, 380, 221, 71))
        self.label_3.setStyleSheet("background-color: #ED2126;\n"
"color:white;\n"
"font: 87 17pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(170, 80, 51, 21))
        self.label_4.setStyleSheet("background-color: #ED2126;\n"
"color:white;\n"
"font: 87 15pt \"Arial \";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(130, 100, 151, 81))
        self.label_5.setStyleSheet("background-color: #ED2126;\n"
"color:white;\n"
"font: 87 15pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(20, 660, 151, 31))
        self.label_6.setStyleSheet("background-color: #ED2126;\n"
"color:white;\n"
"font: 87 10pt \"Arial \";")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(40, 440, 341, 41))
        self.label_8.setStyleSheet("background-color: #ED2126;\n"
"color:white;\n"
"font: 87 10pt \"Arial \";")
        self.label_8.setObjectName("label_8")
        self.label.raise_()
        self.label_3.raise_()
        self.frame_3.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(530, 140, 381, 61))
        self.label_7.setStyleSheet("\n"
"color:#ED2126;\n"
"font: 87 18pt \"Arial Black\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.username = QtWidgets.QLineEdit(self.frame)
        self.username.setGeometry(QtCore.QRect(530, 240, 381, 41))
        self.username.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"    font: 11pt \"Arial\";\n"
"\n"
"}")
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(530, 320, 381, 41))
        self.password.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"    font: 11pt \"Arial\";\n"
"\n"
"}")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.login_button = QtWidgets.QPushButton(self.frame)
        self.login_button.setGeometry(QtCore.QRect(530, 400, 381, 41))
        self.login_button.setAutoFillBackground(False)
        self.login_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 0, 0);\n"
"color:rgb(255, 255, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"border:2px solid  rgb(255, 0, 0);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(184, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.login_button.setCheckable(False)
        self.login_button.setFlat(False)
        self.login_button.setObjectName("login_button")
        self.signup = QtWidgets.QPushButton(self.frame)
        self.signup.setGeometry(QtCore.QRect(540, 490, 371, 28))
        self.signup.setStyleSheet("QPushButton{\n"
"color:rgb(84, 107, 255);\n"
"    font: 87 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(184, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.signup.setObjectName("signup")
        self.show_password = QtWidgets.QCheckBox(self.frame)
        self.show_password.setGeometry(QtCore.QRect(881, 330, 21, 20))
        self.show_password.setText("")
        self.show_password.setObjectName("show_password")
        self.button_forgot = QtWidgets.QPushButton(self.frame)
        self.button_forgot.setGeometry(QtCore.QRect(540, 460, 371, 28))
        self.button_forgot.setStyleSheet("QPushButton{\n"
"color:rgb(84, 107, 255);\n"
"    font: 87 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(184, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.button_forgot.setObjectName("button_forgot")
        self.horizontalLayout_2.addWidget(self.frame)
        Login_Screen.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login_Screen)
        QtCore.QMetaObject.connectSlotsByName(Login_Screen)

    def retranslateUi(self, Login_Screen):
        _translate = QtCore.QCoreApplication.translate
        Login_Screen.setWindowTitle(_translate("Login_Screen", "Iniciar sessão"))
        self.label_3.setText(_translate("Login_Screen", "BUFFER RP"))
        self.label_4.setText(_translate("Login_Screen", "Olá"))
        self.label_5.setText(_translate("Login_Screen", "Bem-vindo à !"))
        self.label_6.setText(_translate("Login_Screen", "© Rajendra Pandit"))
        self.label_8.setText(_translate("Login_Screen", "\"A sua primeira linha de defesa na era digital \""))
        self.label_7.setText(_translate("Login_Screen", "Iniciar sessão"))
        self.username.setPlaceholderText(_translate("Login_Screen", "Email / Nome de Utilizador"))
        self.password.setPlaceholderText(_translate("Login_Screen", "Senha"))
        self.login_button.setText(_translate("Login_Screen", "Entrar"))
        self.signup.setText(_translate("Login_Screen", "Não tens conta ? criar agora"))
        self.button_forgot.setText(_translate("Login_Screen", "Esqueci a palavra-passe"))
import Signup_Screen_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_Screen = QtWidgets.QMainWindow()
    ui = Ui_Login_Screen()
    ui.setupUi(Login_Screen)
    Login_Screen.show()
    sys.exit(app.exec_())
