# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\BufferRP\resources\UI\Signup_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signup_screen(object):
    def setupUi(self, signup_screen):
        signup_screen.setObjectName("signup_screen")
        signup_screen.resize(1001, 713)
        signup_screen.setMinimumSize(QtCore.QSize(1001, 713))
        signup_screen.setMaximumSize(QtCore.QSize(1001, 713))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\BufferRP\\resources\\UI\\Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        signup_screen.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(signup_screen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:white;\n"
"border-style:none;\n"
"border-radius:20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 491, 691))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 491, 691))
        self.label.setStyleSheet("border-radius:20px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Image/RedBanner.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(100, 210, 191, 171))
        self.frame_3.setStyleSheet("border-radius:60px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 151, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Image/Logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(110, 390, 201, 51))
        self.label_3.setStyleSheet("background-color: #ED2126;\n"
"color:white;\n"
"font: 87 17pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(180, 90, 51, 21))
        self.label_4.setStyleSheet("background-color: #ED2126;\n"
"color:white;\n"
"font: 87 15pt \"Arial \";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(130, 100, 151, 81))
        self.label_5.setStyleSheet("background-color: #ED2126;\n"
"color:white;\n"
"font: 87 15pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(20, 660, 151, 31))
        self.label_6.setStyleSheet("background-color: #ED2126;\n"
"color:white;\n"
"font: 87 10pt \"Arial \";")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(40, 440, 361, 51))
        self.label_8.setStyleSheet("background-color: #ED2126;\n"
"color:white;\n"
"font: 87 10pt \"Arial \";")
        self.label_8.setObjectName("label_8")
        self.label.raise_()
        self.label_3.raise_()
        self.frame_3.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(620, 100, 251, 81))
        self.label_7.setStyleSheet("\n"
"color:#ED2126;\n"
"font: 87 18pt \"Arial Black\";")
        self.label_7.setObjectName("label_7")
        self.username = QtWidgets.QLineEdit(self.frame)
        self.username.setGeometry(QtCore.QRect(530, 210, 381, 41))
        self.username.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"    font: 11pt \"Arial\";\n"
"\n"
"}")
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(530, 370, 381, 41))
        self.password.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"    font: 11pt \"Arial\";\n"
"\n"
"}")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.signup_button = QtWidgets.QPushButton(self.frame)
        self.signup_button.setGeometry(QtCore.QRect(530, 450, 381, 41))
        self.signup_button.setAutoFillBackground(False)
        self.signup_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 0, 0);\n"
"color:rgb(255, 255, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"border:2px solid  rgb(255, 0, 0);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(184, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.signup_button.setCheckable(False)
        self.signup_button.setFlat(False)
        self.signup_button.setObjectName("signup_button")
        self.login = QtWidgets.QPushButton(self.frame)
        self.login.setGeometry(QtCore.QRect(540, 520, 361, 28))
        self.login.setStyleSheet("QPushButton{\n"
"color:rgb(84, 107, 255);\n"
"    font: 87 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(184, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.login.setObjectName("login")
        self.email = QtWidgets.QLineEdit(self.frame)
        self.email.setGeometry(QtCore.QRect(530, 290, 381, 41))
        self.email.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"    font: 11pt \"Arial\";\n"
"\n"
"}")
        self.email.setText("")
        self.email.setObjectName("email")
        self.show_password = QtWidgets.QCheckBox(self.frame)
        self.show_password.setGeometry(QtCore.QRect(885, 380, 21, 21))
        self.show_password.setStyleSheet("border-color: rgb(243, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.show_password.setText("")
        self.show_password.setObjectName("show_password")
        self.verticalLayout.addWidget(self.frame)
        signup_screen.setCentralWidget(self.centralwidget)

        self.retranslateUi(signup_screen)
        QtCore.QMetaObject.connectSlotsByName(signup_screen)

    def retranslateUi(self, signup_screen):
        _translate = QtCore.QCoreApplication.translate
        signup_screen.setWindowTitle(_translate("signup_screen", "Registar"))
        self.label_3.setText(_translate("signup_screen", "BUFFER RP"))
        self.label_4.setText(_translate("signup_screen", "Olá"))
        self.label_5.setText(_translate("signup_screen", "Bem-vindo à !"))
        self.label_6.setText(_translate("signup_screen", "© Rajendra Pandit"))
        self.label_8.setText(_translate("signup_screen", "\"A Sua primeira linha de defesa na era digital \""))
        self.label_7.setText(_translate("signup_screen", "Registar-se"))
        self.username.setPlaceholderText(_translate("signup_screen", "Nome de utilizador"))
        self.password.setPlaceholderText(_translate("signup_screen", "Senha"))
        self.signup_button.setText(_translate("signup_screen", "Criar"))
        self.login.setText(_translate("signup_screen", "Já tenho uma conta"))
        self.email.setPlaceholderText(_translate("signup_screen", "Email"))
import Signup_Screen_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    signup_screen = QtWidgets.QMainWindow()
    ui = Ui_signup_screen()
    ui.setupUi(signup_screen)
    signup_screen.show()
    sys.exit(app.exec_())
